version: '3'

services:
  dpm_service:
    build:
      context: .
      dockerfile: src/python/dpm/Dockerfile
    container_name: dpm_container
    volumes:
      - ./data:/app/data

  am_service:
    build:
      context: ./src/cpp/am
      dockerfile: Dockerfile
    restart: always
