@startuml Security Design - Package Diagram

package "CARE System" {
    [User Interface] as UI
    [Data Collection Module] as DCM
    [Data Preprocessing Module] as DPM
    [Alerting Module] as AM
    [Visualization & Reporting Module] as VRM
}

[User Authentication] -down- UI
[Data Encryption] -down- DCM
[Data Integrity Check] -down- DPM
[Secure Communication] -down- AM
[Secure Visualization] -down- VRM

@enduml
